* Nix-Docker-Nix

An attempt to fully configure Docker image with a ready-to-use Nix
environment.

** Prior work
   
This work would not be possible without 

** Goals

Goals are listed in order of importance. Once goal is reached it will be crossed
over.

*** #. Easy to try out Nix in a Docker container ([0/3])

Currently installation story is not perfect. A lot of potential users are
feeling overwhelmed by the amount of installation steps and options. While
options are always good to have, having to much of them at first only confuses
potential users.

At the same time we also must admit that Docker is some sort of industry
standard. For this project we can assume that most potential users will have
basic Docker knowledge. (/I'm aware this are not all of our potential users,
this project does not try to make it work for everybody./)

Tasks:

- [ ] Build a Docker image with Nix and configure Nix to be running without
      sandbox mode.
  
  This would allow potential users to get Nix environment by typing:
   
  #+BEGIN_SRC shell
    $ docker run -ti nixos/nix:latest
  #+END_SRC

- [ ] Test Nix installation on each commit to Nix repository.

  https://github.com/grahamc/nix-install-matrix/tree/refactored-hacks
  
- [ ] Build a Docker image with Nix and configure Nix to be running with enabled
  sandbox mode.
  
  This would allow potential users to get Nix environment by typing:

  #+BEGIN_SRC shell
    $ docker run -ti nixos/nix-sandbox:latest
  #+END_SRC
  
- [ ] Build a Docker image with Nix and configure Nix to be running with enabled
  multiuser mode.
  
  This would allow potential users to get Nix environment by typing:

  #+BEGIN_SRC shell
    $ docker run -ti nixos/nix-multiuser:latest
  #+END_SRC
  
*** #. Companies using Docker and Nix should be able to extend on this work

*** #. Improve documentation and messaging how and why to build Docker images with Nix

** Want to help? Need help?

Look at currently open issues and get engaged.
Looking for help? Open an issue.

https://github.com/nix-community/nix-docker-nix/issues
